name: CI with Docker Runner

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and test microservices
        run: |
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml up -d db ms1 ms2
          sleep 10  # Espera a que los servicios se levanten
          curl -f http://localhost:3001/health
          curl -f http://localhost:3002/health

      - name: Stop services
        run: docker-compose -f docker-compose.yml down
